package com.javatraining.reflection;

import java.lang.reflect.*;
import java.util.*;
import java.util.function.BiFunction;

/**
 * Module 21 - Dynamic Proxies
 *
 * java.lang.reflect.Proxy creates a proxy object at runtime that implements
 * one or more interfaces. All method calls are dispatched to an InvocationHandler.
 *
 * Key rules:
 *   - Proxy can only implement interfaces, not extend classes
 *   - The proxy class is generated by the JVM at runtime
 *   - InvocationHandler receives (proxy, method, args) for every call
 *
 * Common uses:
 *   - AOP-style cross-cutting concerns (logging, timing, auth)
 *   - Lazy loading / remote proxies (RMI, gRPC stubs)
 *   - Mocking frameworks (Mockito)
 *   - Caching decorators
 *
 * Limitations:
 *   - Interface-only (use CGLIB/ByteBuddy for class proxies)
 *   - Slight runtime overhead vs direct calls
 *   - Harder to debug (stack traces show proxy machinery)
 */
public class DynamicProxy {

    // ── Logging proxy ─────────────────────────────────────────────────────────

    /**
     * Wraps target in a proxy that logs every method call (name + args) to a list.
     * The proxy implements the same interface(s) as target.
     */
    @SuppressWarnings("unchecked")
    public static <T> T loggingProxy(T target, List<String> log) {
        return (T) Proxy.newProxyInstance(
            target.getClass().getClassLoader(),
            target.getClass().getInterfaces(),
            (proxy, method, args) -> {
                log.add(method.getName() + "(" + argsToString(args) + ")");
                return method.invoke(target, args);
            }
        );
    }

    // ── Timing proxy ──────────────────────────────────────────────────────────

    /**
     * Wraps target in a proxy that records elapsed time (ns) for each call.
     * Results are stored in timings as method name → nanoseconds.
     */
    @SuppressWarnings("unchecked")
    public static <T> T timingProxy(T target, Map<String, Long> timings) {
        return (T) Proxy.newProxyInstance(
            target.getClass().getClassLoader(),
            target.getClass().getInterfaces(),
            (proxy, method, args) -> {
                long start = System.nanoTime();
                try {
                    return method.invoke(target, args);
                } finally {
                    timings.put(method.getName(), System.nanoTime() - start);
                }
            }
        );
    }

    // ── Null-guard proxy ──────────────────────────────────────────────────────

    /**
     * Wraps target in a proxy that throws NullPointerException if any argument
     * to any method is null.  Useful for enforcing non-null contracts.
     */
    @SuppressWarnings("unchecked")
    public static <T> T nullGuardProxy(T target) {
        return (T) Proxy.newProxyInstance(
            target.getClass().getClassLoader(),
            target.getClass().getInterfaces(),
            (proxy, method, args) -> {
                if (args != null) {
                    for (int i = 0; i < args.length; i++) {
                        if (args[i] == null) {
                            throw new NullPointerException(
                                "null argument at index " + i
                                + " of " + method.getName());
                        }
                    }
                }
                return method.invoke(target, args);
            }
        );
    }

    // ── Caching proxy ─────────────────────────────────────────────────────────

    /**
     * Wraps target in a proxy that caches return values keyed by
     * (method name + args). Subsequent calls with the same args return cached result.
     * Only caches non-void methods with non-null return values.
     */
    @SuppressWarnings("unchecked")
    public static <T> T cachingProxy(T target) {
        Map<String, Object> cache = new HashMap<>();
        return (T) Proxy.newProxyInstance(
            target.getClass().getClassLoader(),
            target.getClass().getInterfaces(),
            (proxy, method, args) -> {
                if (method.getReturnType() == void.class) {
                    return method.invoke(target, args);
                }
                String key = method.getName() + Arrays.toString(args);
                if (cache.containsKey(key)) return cache.get(key);
                Object result = method.invoke(target, args);
                if (result != null) cache.put(key, result);
                return result;
            }
        );
    }

    // ── Retry proxy ───────────────────────────────────────────────────────────

    /**
     * Wraps target in a proxy that retries any method that throws an exception,
     * up to maxRetries times.  Throws the last exception if all retries fail.
     */
    @SuppressWarnings("unchecked")
    public static <T> T retryProxy(T target, int maxRetries) {
        return (T) Proxy.newProxyInstance(
            target.getClass().getClassLoader(),
            target.getClass().getInterfaces(),
            (proxy, method, args) -> {
                Exception lastException = null;
                for (int attempt = 0; attempt <= maxRetries; attempt++) {
                    try {
                        return method.invoke(target, args);
                    } catch (InvocationTargetException e) {
                        lastException = e;
                    }
                }
                throw lastException;
            }
        );
    }

    // ── Read-only proxy ───────────────────────────────────────────────────────

    /**
     * Wraps target in a proxy that throws UnsupportedOperationException for any
     * method whose name starts with "set" or "add" or "remove" or "clear".
     */
    @SuppressWarnings("unchecked")
    public static <T> T readOnlyProxy(T target) {
        Set<String> mutatingPrefixes = Set.of("set", "add", "remove", "clear", "put", "delete");
        return (T) Proxy.newProxyInstance(
            target.getClass().getClassLoader(),
            target.getClass().getInterfaces(),
            (proxy, method, args) -> {
                String name = method.getName();
                for (String prefix : mutatingPrefixes) {
                    if (name.startsWith(prefix)) {
                        throw new UnsupportedOperationException(
                            "read-only proxy: " + name + " is not allowed");
                    }
                }
                return method.invoke(target, args);
            }
        );
    }

    // ── Proxy introspection ───────────────────────────────────────────────────

    /** Returns true if obj was created by Proxy.newProxyInstance. */
    public static boolean isProxy(Object obj) {
        return Proxy.isProxyClass(obj.getClass());
    }

    /** Returns the InvocationHandler for a proxy object. */
    public static InvocationHandler getHandler(Object proxy) {
        return Proxy.getInvocationHandler(proxy);
    }

    // ── Generic proxy factory ─────────────────────────────────────────────────

    /**
     * Creates a proxy for a single interface where every method call is
     * dispatched to the provided handler function (method name, args) → result.
     */
    @SuppressWarnings("unchecked")
    public static <T> T createProxy(Class<T> iface,
                                     BiFunction<String, Object[], Object> handler) {
        return (T) Proxy.newProxyInstance(
            iface.getClassLoader(),
            new Class<?>[] { iface },
            (proxy, method, args) -> handler.apply(method.getName(), args)
        );
    }

    // ── Helper ────────────────────────────────────────────────────────────────

    private static String argsToString(Object[] args) {
        if (args == null || args.length == 0) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < args.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(args[i]);
        }
        return sb.toString();
    }
}
