package com.javatraining.jdbc.core;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Creates and tears down the demo schema used throughout Module 31.
 *
 * <p>Two tables:
 * <ul>
 *   <li>{@code products} - catalogue of items with name, price, stock quantity</li>
 *   <li>{@code orders}   - placed orders that reference a product (FK)</li>
 * </ul>
 *
 * <p>{@code IF NOT EXISTS / IF EXISTS} guards make these methods idempotent,
 * so they can be called multiple times without error.
 *
 * <p>Drop order matters: {@code orders} first (FK child), then {@code products}
 * (FK parent).  Creating in the opposite order for the same reason.
 */
public class DatabaseInitializer {

    private DatabaseInitializer() {}

    /** Creates tables if they do not already exist. */
    public static void initialize(Connection conn) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS products (
                        id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name      VARCHAR(100) NOT NULL,
                        price     DECIMAL(10,2) NOT NULL,
                        stock_qty INT NOT NULL DEFAULT 0
                    )
                    """);

            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS orders (
                        id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        product_id  INT NOT NULL,
                        quantity    INT NOT NULL,
                        total_price DECIMAL(10,2) NOT NULL,
                        status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        FOREIGN KEY (product_id) REFERENCES products(id)
                    )
                    """);
        }
    }

    /** Drops both tables in FK-safe order. */
    public static void dropAll(Connection conn) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS orders");
            stmt.execute("DROP TABLE IF EXISTS products");
        }
    }
}
